app = "project-s-backend"
primary_region = "sea"

[build]

[http_service]
internal_port = 8000
force_https = false
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
