# fly.toml app configuration file generated for project-s-backend on 2024-04-26T22:07:46-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-s-backend'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
